import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {pbkdf2Sync} from 'node:crypto';
const require=createRequire(import.meta.url),D=require('./dist/mentor.js'),{CareGame}=require('./dist/engine.js'),{History,csv}=require('./dist/history.js'),A=require('./dist/analytics.js');
const worker=(await import('data:text/javascript;base64,'+fs.readFileSync('dist/server/index.js').toString('base64'))).default;
const sqlite=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const DB={prepare(sql){const q=sqlite.prepare(sql);return{bind(...args){return{async run(){return q.run(...args)},async all(){return{results:q.all(...args)}}}}}}},salt='0123456789abcdef0123456789abcdef',password='Test-instructor-password',env={DB,ADMIN_PASSWORD_HASH:salt+':'+pbkdf2Sync(password,Buffer.from(salt,'hex'),100000,32,'sha256').toString('hex')};let adminCookie='';
let checks=0;const check=(v,label)=>{assert.ok(v,label);checks++};
function req(path,user='',email='',body=null){return new Request('https://game.test'+path,{method:body?'POST':'GET',headers:{Origin:'https://game.test',...(user?{'oai-authenticated-user-id':user}:{}),...(email?{'oai-authenticated-user-email':email}:{}),...(user==='teacher'&&adminCookie?{Cookie:adminCookie}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});}
const prefs={name:'Student Alice',studentCode:'S001',group:'Group A',lang:'en',look:0,outfit:0,pace:25},game=new CareGame(D),h=new History();h.start(prefs);game.start();h.capture(game,prefs,[]);game.choose(0);h.capture(game,prefs,[0,1,2]);const partial=structuredClone(h.current);
while(game.state.phase!=='ending'){if(game.state.phase==='feedback')game.next();else {game.choose(game.node().options.findIndex(o=>o.correctness===2));h.capture(game,prefs,[0,1,2]);}}h.capture(game,prefs,[]);const full=structuredClone(h.current);
check((await worker.fetch(req('/admin'),env)).status===302,'Admin page returns to in-game password form');
check((await worker.fetch(req('/admin','student','student@example.test'),env)).status===302,'Student without password cannot open page');
check((await worker.fetch(req('/api/admin/sessions','teacher','teacher@example.test'),{DB,ADMIN_EMAIL:'teacher@example.test'})).status===401,'Old owner email cannot bypass password');
check((await worker.fetch(req('/api/admin/login','','',{password:'wrong'}),env)).status===401,'Wrong password rejected');
const login=await worker.fetch(req('/api/admin/login','','',{password}),env);check(login.status===200,'Password login allowed without account role');adminCookie=login.headers.get('Set-Cookie').split(';')[0];check(/HttpOnly; Secure; SameSite=Strict/.test(login.headers.get('Set-Cookie')),'Cookie is HttpOnly Secure SameSite');
check((await worker.fetch(req('/admin','teacher'),env)).status===200,'Valid password session opens dashboard');
check((await worker.fetch(req('/api/admin/sessions'),env)).status===401,'Anonymous admin API denied');
check((await worker.fetch(req('/api/admin/sessions','student','student@example.test'),env)).status===401,'Student admin API denied');
check((await worker.fetch(req('/api/admin/sessions','teacher','teacher@example.test'),{DB})).status===401,'Missing password configuration fails closed');
check((await worker.fetch(req('/api/me'),env)).status===200,'Public account check works');check(!(await (await worker.fetch(req('/api/me'),env)).json()).signedIn,'Anonymous cannot start saved play');
check((await (await worker.fetch(req('/api/me','teacher','teacher@example.test'),env)).json()).isAdmin,'Password session is server derived');
check((await worker.fetch(req('/api/admin/sessions?cursor=bad','teacher','teacher@example.test'),env)).status===400,'Bad admin cursor rejected');
await worker.fetch(req('/api/history','alice','alice@example.test',{...full,accountEmail:'teacher@example.test',accountId:'teacher'}),env);
let page=await (await worker.fetch(req('/api/admin/sessions','teacher','teacher@example.test'),env)).json();check(page.sessions[0].accountEmail==='alice@example.test'&&page.sessions[0].accountId==='alice','Instructor identities come from trusted headers and database');check(page.sessions[0].studentCode==='S001'&&page.sessions[0].group==='Group A','Student metadata saved');
await worker.fetch(req('/api/history','bob','bob@example.test',{...partial,id:'bob-first-run',name:'Bob',studentCode:'S002'}),env);
check((await (await worker.fetch(req('/api/history','bob','bob@example.test'),env)).json()).sessions.length===1,'Personal history stays account scoped');
for(let i=0;i<205;i++)await worker.fetch(req('/api/history','account-'+i,'student'+i+'@example.test',{...partial,id:'same-run-id',startedAt:'2026-10-01T00:00:00.000Z'}),env);
let cursor=null,all=[];do{page=await (await worker.fetch(req('/api/admin/sessions'+(cursor?'?cursor='+encodeURIComponent(cursor):''),'teacher','teacher@example.test'),env)).json();all.push(...page.sessions);cursor=page.nextCursor;}while(cursor);
check(all.length===207&&new Set(all.map(s=>s.accountId+'|'+s.id)).size===207,'Admin cursor handles identical dates and session IDs across accounts');
const complete=(id,user,date,score,safety)=>({...full,id,accountId:user,studentCode:user==='alice'?'S001':'S002',startedAt:date,result:{...full.result,safety,knowledge:{...full.result.knowledge,correct:score}}});
const runs=[complete('alice-first','alice','2026-10-01T00:00:00Z',6,80),complete('alice-last','alice','2026-10-02T00:00:00Z',12,100),complete('bob-first','bob','2026-10-01T00:00:00Z',3,60),{...partial,accountId:'charlie',id:'charlie-open',group:'Group B'}];
let selected=A.select(runs,{attempt:'latest'}),stats=A.summarize(selected);check(selected.length===2&&stats.players===2,'Latest completed chooses one per account');check(stats.meanKnowledge===62.5&&stats.meanSafety===80,'Latest completed means calculated correctly');
stats=A.summarize(A.select(runs,{attempt:'first'}));check(stats.meanKnowledge===37.5&&stats.meanSafety===70,'First completed means calculated correctly');
stats=A.summarize(A.select(runs,{attempt:'all'}));check(stats.incomplete===1&&stats.completed===3&&stats.meanSafety===80,'Incomplete excluded from score means');
check(A.select(runs,{attempt:'all',group:'Group B'}).length===1,'Group filter');check(A.select(runs,{attempt:'all',search:'s001'}).length===3,'Case insensitive ID filter');check(A.select(runs,{attempt:'latest',from:'2026-10-02',to:'2026-10-02'}).length===1,'Date filter before attempt selection');
check(A.select([runs[0],{...runs[1],accountId:'another-device'}],{attempt:'latest'}).length===1,'Same class and student ID count once across browsers');
check(A.select([runs[0],{...runs[1],studentCode:'S002'}],{attempt:'latest'}).length===2,'Different students on one browser count separately');
check(A.localDay('2026-10-01T20:00:00Z')==='2026-10-02','Calendar uses Taipei timezone');
const timed={...partial.answers[0],timeout:true,correctness:0,elapsedSeconds:25},sample=[{...runs[0],answers:[full.answers[0],timed]}];stats=A.summarize(sample);check(stats.questions[0].rate===50&&stats.questions[0].timeouts===1,'Timeout included in answered denominator');check(A.summarize([]).meanKnowledge===null,'No data is not a zero score');
const output=csv([{...full,accountId:'alice',accountEmail:'alice@example.test'}],true);check(output.includes('account_email')&&output.includes('alice@example.test'),'Admin replies export includes verified identity');check(output.split('\r\n')[33].includes('"33"'),'Reply numbering is preserved');check(output.split('\r\n').length===34,'All 33 replies exported');
check(sqlite.prepare("SELECT name FROM sqlite_schema WHERE name='idx_play_sessions_started_id_user'").get(),'Global pagination index migrated');
const cross=new Request('https://game.test/api/admin/login',{method:'POST',headers:{Origin:'https://other.test','Content-Type':'application/json'},body:JSON.stringify({password})});check((await worker.fetch(cross,env)).status===403,'Cross-origin password submission denied');
const forged=new Request('https://game.test/api/admin/sessions',{headers:{Cookie:'__Host-care-admin='+'a'.repeat(64)}});check((await worker.fetch(forged,env)).status===401,'Fabricated cookie cannot unlock data');
sqlite.prepare('UPDATE admin_sessions SET expires_at = 0').run();check((await worker.fetch(req('/api/admin/sessions','teacher'),env)).status===401,'Expired session denied');
const again=await worker.fetch(req('/api/admin/login','','',{password}),env);adminCookie=again.headers.get('Set-Cookie').split(';')[0];check((await worker.fetch(req('/api/admin/logout','teacher','',{logout:true}),env)).status===200,'Logout works');check((await worker.fetch(req('/api/admin/sessions','teacher'),env)).status===401,'Logout invalidates server session, including copied cookie');
for(let i=0;i<5;i++)check((await worker.fetch(req('/api/admin/login','','',{password:'wrong'}),env)).status===401,'Incorrect attempt '+i);
check((await worker.fetch(req('/api/admin/login','','',{password}),env)).status===429,'Repeated guesses throttled');
sqlite.close();console.log(JSON.stringify({status:'passed',checks,verified:['instructor authorization','trusted identity','student metadata','multi-account pagination','attempt policies','score denominators','Taipei dates','assessment exports']},null,2));
