import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const D=require('./dist/mentor.js'),{CareGame}=require('./dist/engine.js');
require('./dist/history.js');
let checks=0;const check=(condition,message)=>{assert.ok(condition,message);checks++;};
const locales=['th','zh','en'];
function validateLocalized(value,path='story'){if(!value||typeof value!=='object')return;if('th'in value||'zh'in value||'en'in value){for(const l of locales)check(typeof value[l]==='string'&&value[l].trim().length>0,`Missing ${l}: ${path}`);}else for(const[k,v]of Object.entries(value))validateLocalized(v,path+'.'+k);}
validateLocalized(D);check(D.scenes.length===7,'Seven scenes include briefing and debrief');check(D.nodes.filter(n=>n.academic).length===12,'Twelve pharmacology questions');check(new Set(D.nodes.map(n=>n.id)).size===D.nodes.length,'Unique dialogue IDs');
for(const node of [...D.nodes,...Object.values(D.repairs)]){check(node.options.length>=2&&node.options.length<=3,'Two or three replies');check(node.options.some(o=>o.correctness===2),'Every node offers a safe empathetic response');for(const key of node.sources||[])check(key in D.sources,`Source ${key} exists`);for(const option of node.options){if(option.repair)check(option.repair in D.repairs,'Repair branch exists');for(const k of ['safety','trust','stress'])check(Number.isFinite(option.impact[k]),'Finite impacts');}}
const html=fs.readFileSync('dist/index.html','utf8');for(const [,key]of html.matchAll(/data-i18n="([^"]+)"/g))check(key in D.ui,`Translated UI key ${key}`);for(const [,file]of html.matchAll(/(?:src|href)="([^"#]+)"/g))if(!/^(?:https?:|data:|\/signin-with-chatgpt\?|\/admin$)/.test(file))check(fs.existsSync('dist/'+file),`Asset ${file} exists`);
const css=fs.readFileSync('dist/styles.css','utf8');for(const [,file]of css.matchAll(/url\('([^']+)'\)/g))if(!file.startsWith('https:'))check(fs.existsSync('dist/'+file),`CSS asset ${file} exists`);
for(const npc of ['doctor','caregiver','mentor'])for(const mood of ['neutral','smile','concern','surprise'])check(fs.existsSync(`dist/assets/${npc}-${mood}.webp`),'NPC sprite exists');for(let look=0;look<2;look++)for(let outfit=0;outfit<3;outfit++)check(fs.existsSync(`dist/assets/player-${look}-${outfit}.webp`),'Outfit exists');
for(const n of D.nodes){check(n.scene>=0&&n.scene<D.scenes.length,'Valid scene index');check(['doctor','caregiver','mentor'].includes(n.npc),'Known speaker');if(n.academic){check(n.options.filter(o=>o.correctness===2).length===1,'Academic answer has one correct option');check(n.topic in D.topics,'Known topic');check(n.sources.length>0,'Academic question has evidence');for(const o of n.options){check(o.impact.safety===0,'Academic reply cannot score patient safety');validateLocalized(o.explanation,`explanation.${n.id}`);}}}
function finish(g,policy){let guard=0;while(g.state.phase!=='ending'){check(++guard<100,'Story terminates');if(g.state.phase==='feedback')g.next();else g.choose(policy(g.node(),g));}return g.outcome();}
let g=new CareGame(D);g.start(25);let perfect=finish(g,n=>n.options.findIndex(o=>o.correctness===2));check(perfect.id==='harmony','Perfect play reaches harmony');check(perfect.unresolved.length===0,'No unresolved risks on perfect route');check(perfect.decisions===D.nodes.length,'All main nodes played');
check(perfect.knowledge.correct===12&&perfect.knowledge.answered===12,'Perfect knowledge score');
for(const [expected,pattern]of [['connection',5],['safe',3]]){g=new CareGame(D);g.start();let k=0;const result=finish(g,n=>{if(n.npc==='mentor')return n.options.findIndex(o=>o.correctness===2);const options=n.options.map((o,i)=>({o,i})).filter(x=>x.o.correctness>0).sort((a,b)=>a.o.impact.trust-b.o.impact.trust);return k++%5<pattern?options[0].i:options.at(-1).i;});check(result.id===expected,`Distinct emotional ending ${expected} reachable with safe choices`);}
function until(g,id){let guard=0;while(g.node()?.id!==id){check(++guard<70,'Target node reached');g.choose(g.node().options.findIndex(o=>o.correctness===2));g.next();}}
g=new CareGame(D);g.start(15);until(g,'swallow');const parent=g.state.index;g.choose(g.node().options.findIndex(o=>o.repair==='swallowRepair'));check(g.state.unresolved.includes('swallow'),'Unsafe swallowing flagged');g.next();check(g.node().id==='repair-swallow','Correct repair branch');check(g.node().scene===1,'Repair scene follows parent after briefing');g.choose(0);g.next();check(!g.state.unresolved.includes('swallow'),'Repair clears swallowing flag');check(g.state.index===parent+1,'Repair rejoins main route');
g=new CareGame(D);g.start(25);until(g,'final');g.choose(0);g.next();const unsafeCase=JSON.stringify(g.state.caseResult);check(g.outcome().id==='review','Unsafe final decision cannot be rescued by high trust');const unsafePerfectExam=finish(g,n=>n.options.findIndex(o=>o.correctness===2));check(unsafePerfectExam.knowledge.correct===12,'Perfect exam available after unsafe care');check(unsafePerfectExam.id==='review'&&JSON.stringify(g.state.caseResult)===unsafeCase,'Perfect exam cannot repair an unsafe clinical result');
g=new CareGame(D);g.start(25);until(g,'final');g.tick(25);g.next();check(g.outcome().id==='review','Final timeout cannot approve discharge');check(g.outcome().timeouts===1&&g.outcome().clinicalTimeouts===1,'Clinical timeout count correct');
g=new CareGame(D);g.start(25);until(g,'mentor-return');const safeCase=JSON.stringify(g.state.caseResult),safetyBefore=g.state.safety;const poorExam=finish(g,n=>n.academic?n.options.findIndex(o=>o.correctness===0):n.options.findIndex(o=>o.correctness===2));check(poorExam.knowledge.correct===0&&poorExam.knowledge.answered===12,'All incorrect answers earn zero academic points');check(poorExam.id==='harmony'&&g.state.safety===safetyBefore&&JSON.stringify(g.state.caseResult)===safeCase,'Poor exam does not rewrite completed patient care');
g=new CareGame(D);g.start(15);until(g,'pk-ionization');check(g.state.budget===23&&g.state.remaining===23,'Deeper question gets rounded 1.5x budget');g.tick(23);check(g.state.feedback.timeout&&g.state.knowledge.answered===1&&g.state.knowledge.correct===0,'Academic timeout counts as one unanswered-correct question');check(g.state.feedback.impact.safety===0,'Academic timeout has no safety impact');const scoreBefore=g.state.knowledge.answered;assert.throws(()=>g.choose(0));check(g.state.knowledge.answered===scoreBefore,'Duplicate reply cannot earn a second point');g.next();check(g.state.remaining===23,'Next academic question resets extended budget');
g=new CareGame(D);g.start(45);g.tick(7);check(g.state.remaining===38,'Elapsed time tracked');g.choose(0);g.tick(500);check(g.state.remaining===38,'Feedback is untimed');assert.throws(()=>g.choose(0));g.next();check(g.state.remaining===45,'New reply gets full selected budget');assert.throws(()=>g.tick(-1));assert.throws(()=>g.choose(99));assert.throws(()=>g.start(0));
let seed=731;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;};const endings=new Set();for(let run=0;run<80;run++){g=new CareGame(D);g.start([15,25,45][run%3]);finish(g,(n,game)=>{for(const p of Object.values(game.state.people))check(p.trust>=0&&p.trust<=100&&p.stress>=0&&p.stress<=100,'Meters remain bounded');check(game.state.safety>=0&&game.state.safety<=100,'Safety bounded');check(game.state.knowledge.correct<=game.state.knowledge.answered&&game.state.knowledge.answered<=12,'Knowledge counts remain valid');return Math.floor(random()*n.options.length);});endings.add(g.outcome().id);}
console.log(JSON.stringify({status:'passed',checks,scenes:D.scenes.length,mainDecisions:D.nodes.length,academicQuestions:12,repairBranches:Object.keys(D.repairs).length,languages:locales,outfitCombinations:6,perfectOutcome:perfect.id,knowledgeSeparatedFromSafety:true,randomOutcomes:[...endings]},null,2));
